name: (k8s package) Publish Test Base Image
on:
  push:
    tags:
      # we only need base image for k8s based tests
      - 'lib/v*'
  workflow_dispatch:

jobs:
  publish_test_base_image:
    runs-on: ubuntu-latest
    environment: integration
    permissions:
      id-token: write
      contents: read
    env:
      BASE_IMAGE_TAG: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/test-base-image:${{ github.ref_name }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Strip "lib/" from github.ref_name
        run: |
          stripped_ref_name="${GITHUB_REF//refs\/tags\/lib\//}"
          # disabling as the string containing variable is double-quotted as a whole, no need to quote each variable separately
          # shellcheck disable=SC2086          
          echo "BASE_IMAGE_TAG=${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/test-base-image:$stripped_ref_name" >> $GITHUB_ENV

      - name: Build Base Image
        uses: smartcontractkit/chainlink-github-actions/docker/build-push@d1fce734a6210acb41a8bbbb0cc81301e47aee89 # v2.3.32
        with:
          tags: ${{ env.BASE_IMAGE_TAG }}
          file: lib/k8s/Dockerfile.base
          AWS_REGION: ${{ secrets.QA_AWS_REGION }}
          AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
