name: Module graph
on:
  pull_request:
jobs:
  modgraph:
    runs-on: ubuntu-latest
    name: modgraph
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Go
        uses: actions/setup-go@v5
      - run: make modgraph
      - name: Ensure clean modgraph
        run: git diff --minimal --exit-code
